services:
  # Spring Boot 3.4.1 (Java 21) Backend Web Service
  - type: web
    name: accessaudit-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-solitary-dream-b5zgys0c.c-7.us-east-2.aws.neon.tech:5432/neondb?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_ToN2zbi4EAFH
      - key: APP_JWT_SECRET
        value: MTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MDE=
