import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Sparkles, Scan, Globe, AlertTriangle, CheckCircle, ShieldCheck, 
  Code2, Download, Copy, Check, ArrowRight, ExternalLink, RefreshCw, Zap,
  MapPin, Eye, HelpCircle, Layers, ChevronDown, ChevronUp
} from 'lucide-react';
import { toast } from 'react-toastify';
import { scanWebsite } from '../services/scannerService';
import ScoreCard from '../components/ScoreCard';
import { Card, CardHeader, CardContent } from '../components/ui/Card';
import Button from '../components/ui/Button';

const AIScanner = () => {
  const [url, setUrl] = useState('https://www.cuchd.in');
  const [isScanning, setIsScanning] = useState(false);
  const [scanStep, setScanStep] = useState(0);
  const [results, setResults] = useState(null);
  const [copiedId, setCopiedId] = useState(null);
  const [activeFilter, setActiveFilter] = useState('ALL');
  const [expandedStepId, setExpandedStepId] = useState(null);
  const [showVisualMap, setShowVisualMap] = useState(true);
  const [showPassedModal, setShowPassedModal] = useState(false);

  const handleScoreCardClick = (filterType, toastMsg) => {
    setActiveFilter(filterType);
    const element = document.getElementById('remediation-diagnostics-card');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
    if (toastMsg) toast.info(toastMsg);
  };

  const scanSteps = [
    'Connecting to website DOM...',
    'Evaluating WCAG 2.1 AA Color Contrast & Typography...',
    'Auditing ARIA roles, ALT attributes & Keyboard Focus...',
    'Generating AI-Powered Code Remediation Fixes...'
  ];

  const handleStartScan = async (e) => {
    if (e) e.preventDefault();
    if (!url.trim()) {
      toast.error('Please enter a valid website URL.');
      return;
    }

    setIsScanning(true);
    setResults(null);
    setScanStep(0);

    const stepInterval = setInterval(() => {
      setScanStep((prev) => (prev < scanSteps.length - 1 ? prev + 1 : prev));
    }, 500);

    try {
      const data = await scanWebsite(url);
      clearInterval(stepInterval);
      setResults(data);
      toast.success('AI Audit completed successfully!');
    } catch (error) {
      clearInterval(stepInterval);
      toast.error('Failed to analyze the specified URL.');
    } finally {
      setIsScanning(false);
    }
  };

  const handleCopyCode = (text, id) => {
    navigator.clipboard.writeText(text);
    setCopiedId(id);
    toast.success('AI Code Fix copied to clipboard!');
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleExportReport = () => {
    if (!results) return;

    const reportContent = `# AccessAudit - AI Web Accessibility Scan Report
**Target URL:** ${url}
**Scan Timestamp:** ${new Date().toLocaleString()}
**Overall WCAG 2.1 AA Score:** ${results.score}/100

---

## Executive Summary
- **Critical Violations:** ${results.summary.critical}
- **High Impact Issues:** ${results.summary.high}
- **Passed Rules:** ${results.summary.passed} / ${results.summary.totalRulesChecked}

---

## Detailed WCAG Diagnostics & AI Code Fixes

${results.issues.map((issue, idx) => `
### ${idx + 1}. [${issue.id.toUpperCase()}] ${issue.rule}
- **Impact Level:** ${issue.impact}
- **Category:** ${issue.category}
- **Target Selector:** \`${issue.element}\`
- **Page Location:** ${issue.pageZone || 'Page Content'}

#### 🗣️ Simple Explanation:
${issue.simpleLanguage || issue.description}

#### ⚠️ Main Problem (Who is affected):
${issue.mainProblem || issue.description}

#### ✨ After Fix Look & Behavior:
${issue.afterFixLook || issue.remediation}

#### Non-Compliant HTML Snippet:
\`\`\`html
${issue.snippet}
\`\`\`

#### AI Suggested Code Fix:
\`\`\`html
${issue.aiFix}
\`\`\`

> **AI Remediation Guidance:** ${issue.remediation}
`).join('\n\n---\n')}

---
*Generated by AccessAudit Campus Inclusion Platform*
`;

    const blob = new Blob([reportContent], { type: 'text/markdown;charset=utf-8;' });
    const blobUrl = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = blobUrl;
    link.setAttribute('download', `AccessAudit_AI_Report_${url.replace(/[^a-z0-9]/gi, '_')}.md`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(blobUrl);

    toast.success('Executive AI Audit Report downloaded!');
  };

  const filteredIssues = results?.issues.filter((issue) => {
    if (activeFilter === 'ALL') return true;
    return issue.impact === activeFilter;
  }) || [];

  return (
    <div className="space-y-8 animate-fade-in pb-12">
      {/* Page Header */}
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
        <div>
          <h2 className="text-3xl font-heading font-extrabold text-textMain flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary to-emerald-600 flex items-center justify-center text-white shadow-lg shadow-primary/20">
              <Sparkles size={22} />
            </div>
            AI Web Accessibility Scanner
          </h2>
          <p className="text-textLight mt-1.5 font-medium">
            Scan university web applications for WCAG 2.1 AA compliance & receive instant AI code fixes.
          </p>
        </div>

        {results && (
          <Button
            icon={Download}
            onClick={handleExportReport}
            className="shadow-md"
          >
            Export Audit Report
          </Button>
        )}
      </div>

      {/* URL Scanner Search Card */}
      <Card className="p-6 bg-gradient-to-r from-white via-emerald-50/20 to-primary/5 border border-primary/20 shadow-xl">
        <form onSubmit={handleStartScan} className="space-y-4">
          <label className="block text-sm font-bold text-textMain uppercase tracking-wider">
            Target Web Application URL
          </label>

          <div className="flex flex-col sm:flex-row gap-3">
            <div className="relative flex-1">
              <div className="absolute inset-y-0 left-0 pl-3.5 flex items-center pointer-events-none text-gray-400">
                <Globe size={20} />
              </div>
              <input
                type="text"
                value={url}
                onChange={(e) => setUrl(e.target.value)}
                placeholder="https://www.example.edu"
                disabled={isScanning}
                className="w-full pl-11 pr-4 py-3.5 bg-white border border-gray-200 rounded-xl focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent text-textMain font-medium shadow-sm transition-all"
              />
            </div>

            <Button
              type="submit"
              isLoading={isScanning}
              icon={Zap}
              className="py-3.5 px-8 text-base shadow-lg shadow-primary/20 flex-shrink-0"
            >
              {isScanning ? 'Auditing Page...' : 'Run AI Audit'}
            </Button>
          </div>

          {/* Quick Presets */}
          <div className="flex items-center gap-2 flex-wrap pt-2">
            <span className="text-xs font-semibold text-textLight">Quick Presets:</span>
            {['https://www.cuchd.in', 'https://lms.cuchd.in', 'https://uims.cuchd.in'].map((preset) => (
              <button
                key={preset}
                type="button"
                onClick={() => {
                  setUrl(preset);
                }}
                disabled={isScanning}
                className="text-xs bg-white border border-gray-200 hover:border-primary/50 text-gray-700 px-3 py-1.5 rounded-lg transition-all shadow-xs font-mono hover:text-primary"
              >
                {preset}
              </button>
            ))}
          </div>
        </form>
      </Card>

      {/* Scanning Animation */}
      <AnimatePresence>
        {isScanning && (
          <motion.div
            initial={{ opacity: 0, y: 15 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -15 }}
            className="p-8 glass-panel rounded-2xl border border-primary/30 flex flex-col items-center justify-center text-center space-y-5"
          >
            <div className="relative flex items-center justify-center w-20 h-20">
              <motion.div
                animate={{ rotate: 360 }}
                transition={{ duration: 3, repeat: Infinity, ease: 'linear' }}
                className="absolute inset-0 rounded-full border-4 border-dashed border-primary/30"
              />
              <motion.div
                animate={{ scale: [0.8, 1.15, 0.8] }}
                transition={{ duration: 1.5, repeat: Infinity }}
                className="w-10 h-10 rounded-full bg-primary text-white flex items-center justify-center shadow-lg shadow-primary/30"
              >
                <Scan size={24} />
              </motion.div>
            </div>

            <div>
              <p className="text-lg font-extrabold text-textMain font-heading">
                AI Accessibility Scanner Active
              </p>
              <p className="text-sm font-semibold text-primary mt-1 animate-pulse">
                {scanSteps[scanStep]}
              </p>
            </div>

            <div className="w-64 h-2 bg-gray-100 rounded-full overflow-hidden">
              <motion.div
                className="h-full bg-primary"
                initial={{ width: '0%' }}
                animate={{ width: `${((scanStep + 1) / scanSteps.length) * 100}%` }}
                transition={{ duration: 0.4 }}
              />
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Audit Results Dashboard */}
      {results && !isScanning && (
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-8"
        >
          {/* Overview Score Cards - Interactive Filter Triggers */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <ScoreCard
              title="WCAG 2.1 Score"
              value={`${results.score}/100`}
              colorClass={results.score >= 80 ? 'text-success bg-success-50' : 'text-primary bg-primary-50'}
              icon={<ShieldCheck size={24} />}
              onClick={() => handleScoreCardClick('ALL', 'Showing complete WCAG Audit Report (All Issues)')}
            />
            <ScoreCard
              title="Critical Violations"
              value={results.summary.critical}
              colorClass="text-danger bg-danger-50"
              icon={<AlertTriangle size={24} />}
              onClick={() => handleScoreCardClick('CRITICAL', 'Filtered report to Critical Violations')}
            />
            <ScoreCard
              title="High Impact Issues"
              value={results.summary.high}
              colorClass="text-amber-600 bg-amber-50"
              icon={<AlertTriangle size={24} />}
              onClick={() => handleScoreCardClick('HIGH', 'Filtered report to High Impact Issues')}
            />
            <ScoreCard
              title="Passed Rules"
              value={`${results.summary.passed}/${results.summary.totalRulesChecked}`}
              colorClass="text-emerald-600 bg-emerald-50"
              icon={<CheckCircle size={24} />}
              onClick={() => setShowPassedModal(true)}
            />
          </div>

          {/* Interactive Visual Page Location Map Box */}
          <Card className="border border-blue-200/80 bg-gradient-to-br from-blue-50/40 via-white to-emerald-50/20 shadow-md">
            <CardHeader className="flex flex-row items-center justify-between pb-2 border-b border-gray-100">
              <div className="flex items-center gap-2.5">
                <div className="p-2 rounded-xl bg-blue-500/10 text-blue-600">
                  <MapPin size={20} />
                </div>
                <div>
                  <h3 className="text-lg font-heading font-bold text-textMain flex items-center gap-2">
                    Visual Page Layout & Element Location Map
                  </h3>
                  <p className="text-xs text-textLight font-medium">
                    Numbered visual overlays showing exactly where each violation lies on <span className="font-mono text-primary font-bold">{url}</span>
                  </p>
                </div>
              </div>

              <button
                onClick={() => setShowVisualMap(!showVisualMap)}
                className="flex items-center gap-1 text-xs font-bold text-blue-600 hover:text-blue-800 bg-blue-50 px-3 py-1.5 rounded-lg transition-colors"
              >
                {showVisualMap ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                {showVisualMap ? 'Hide Visual Map' : 'Show Visual Map'}
              </button>
            </CardHeader>

            {showVisualMap && (
              <CardContent className="pt-4 space-y-4">
                {/* Simulated Web Page Frame */}
                <div className="relative rounded-2xl border border-gray-200 bg-white p-4 shadow-inner space-y-3 overflow-hidden font-sans">
                  {/* Browser Bar Header */}
                  <div className="flex items-center justify-between bg-gray-100 px-3 py-2 rounded-xl text-xs text-gray-500 font-mono">
                    <div className="flex items-center gap-1.5">
                      <div className="w-2.5 h-2.5 rounded-full bg-red-400" />
                      <div className="w-2.5 h-2.5 rounded-full bg-amber-400" />
                      <div className="w-2.5 h-2.5 rounded-full bg-emerald-400" />
                      <span className="ml-2 font-bold text-gray-700">{url}</span>
                    </div>
                    <span className="text-[10px] bg-white px-2 py-0.5 rounded border">DOM Visual Inspector Mode</span>
                  </div>

                  {/* Header & Navbar Section */}
                  <div className="relative p-3 rounded-xl bg-gray-50 border border-dashed border-gray-300 space-y-2">
                    <div className="flex items-center justify-between flex-wrap gap-2">
                      <div className="font-black text-sm text-gray-800 flex items-center gap-2">
                        🏫 Campus Portal Header
                      </div>

                      {/* Pin #2: Quick Links Contrast */}
                      <div className="relative group">
                        <span className="inline-flex items-center gap-1 text-xs font-extrabold px-3 py-1 bg-amber-100 text-amber-900 border border-amber-300 rounded-lg animate-pulse">
                          <span className="w-5 h-5 rounded-full bg-amber-600 text-white text-[10px] flex items-center justify-center font-black">#2</span>
                          Quick Links (Low Contrast)
                        </span>
                      </div>

                      {/* Pin #3: Search Bar Name */}
                      <div className="relative group">
                        <span className="inline-flex items-center gap-1 text-xs font-extrabold px-3 py-1 bg-amber-100 text-amber-900 border border-amber-300 rounded-lg animate-pulse">
                          <span className="w-5 h-5 rounded-full bg-amber-600 text-white text-[10px] flex items-center justify-center font-black">#3</span>
                          Search Box (Missing Label)
                        </span>
                      </div>
                    </div>

                    {/* Pin #4: Navigation Menu Links */}
                    <div className="flex gap-3 text-xs font-bold text-gray-600 border-t border-gray-200 pt-2 flex-wrap">
                      <span className="px-2 py-1 bg-red-100 text-red-900 rounded border border-red-300 flex items-center gap-1">
                        <span className="w-4 h-4 rounded-full bg-red-600 text-white text-[9px] flex items-center justify-center font-bold">#4</span>
                        Nav Menu Links (Outline Disabled)
                      </span>
                      <span className="opacity-50">Academics</span>
                      <span className="opacity-50">Admissions</span>
                      <span className="opacity-50">Campus Life</span>
                    </div>
                  </div>

                  {/* Top Hero Banner Section - Pin #1 */}
                  <div className="relative p-6 rounded-xl bg-gradient-to-r from-red-500/10 via-amber-500/10 to-rose-500/10 border-2 border-dashed border-red-400 text-center space-y-2">
                    <div className="absolute top-2 left-2 flex items-center gap-1.5 bg-red-600 text-white text-[11px] font-black px-3 py-1 rounded-full shadow-md">
                      <span className="w-5 h-5 rounded-full bg-white text-red-600 flex items-center justify-center text-[10px]">#1</span>
                      CRITICAL: Hero Banner (Missing ALT Text)
                    </div>
                    <div className="pt-4 font-extrabold text-base text-gray-800">
                      [ 📸 Top Announcement Banner Image: hero-2026.png ]
                    </div>
                    <p className="text-xs text-gray-600 font-medium max-w-lg mx-auto">
                      Visual Guide: Main top image banner displaying university announcements at the top center of the web page.
                    </p>
                  </div>

                  {/* Main Content Body Feed - Pin #5 */}
                  <div className="relative p-4 rounded-xl bg-gray-50 border border-dashed border-gray-300 flex items-center justify-between flex-wrap gap-2">
                    <div className="flex items-center gap-2">
                      <span className="w-5 h-5 rounded-full bg-blue-600 text-white text-[10px] flex items-center justify-center font-black">#5</span>
                      <div>
                        <div className="text-xs font-bold text-gray-800">Main Content Heading ("Academic Calendar 2026")</div>
                        <div className="text-[11px] text-gray-500">Styled using generic &lt;div&gt; instead of semantic &lt;h2&gt; heading</div>
                      </div>
                    </div>
                    <span className="text-[11px] font-mono bg-blue-50 text-blue-700 px-2.5 py-1 rounded border border-blue-200">
                      div.header-title-text
                    </span>
                  </div>
                </div>
              </CardContent>
            )}
          </Card>

          {/* Detailed Findings & AI Remediation */}
          <div id="remediation-diagnostics-card">
            <Card>
              <CardHeader className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
                <div>
                  <h3 className="text-xl font-heading font-bold text-textMain flex items-center gap-2">
                    <Code2 className="text-primary" /> AI Remediation Diagnostics
                  </h3>
                  <p className="text-xs text-textLight font-medium mt-0.5">
                    Showing detected WCAG compliance issues, exact page locations, and AI-generated code solutions.
                  </p>
                </div>

                {/* Impact Filters */}
                <div className="flex bg-gray-100 p-1 rounded-xl gap-1 text-xs font-bold">
                  {['ALL', 'CRITICAL', 'HIGH', 'MEDIUM'].map((filter) => (
                    <button
                      key={filter}
                      onClick={() => setActiveFilter(filter)}
                      className={`px-3 py-1.5 rounded-lg transition-all ${
                        activeFilter === filter
                          ? 'bg-white text-primary shadow-sm'
                          : 'text-gray-600 hover:text-textMain'
                      }`}
                    >
                      {filter}
                    </button>
                  ))}
                </div>
              </CardHeader>

              <CardContent className="space-y-6 pt-4">
                {filteredIssues.map((issue, idx) => (
                  <div
                    key={issue.id}
                    className="p-5 rounded-2xl border border-gray-100 bg-white/60 shadow-sm space-y-4 hover:border-primary/30 transition-all"
                  >
                    <div className="flex flex-wrap items-start justify-between gap-3">
                      <div className="space-y-1.5">
                        <div className="flex items-center gap-2.5 flex-wrap">
                          <span className="text-xs font-mono font-bold px-2.5 py-1 bg-gray-100 text-gray-700 rounded-md">
                            #{idx + 1} {issue.id.toUpperCase()}
                          </span>
                          <span
                            className={`text-xs font-extrabold px-2.5 py-1 rounded-full ${
                              issue.impact === 'CRITICAL'
                                ? 'bg-red-50 text-red-700 border border-red-200'
                                : issue.impact === 'HIGH'
                                ? 'bg-amber-50 text-amber-700 border border-amber-200'
                                : 'bg-blue-50 text-blue-700 border border-blue-200'
                            }`}
                          >
                            {issue.impact} IMPACT
                          </span>
                          <span className="text-xs font-semibold text-textLight">
                            Category: <strong>{issue.category}</strong>
                          </span>
                        </div>

                        <h4 className="text-base font-bold text-textMain font-heading mt-1">
                          {issue.rule}
                        </h4>
                      </div>

                      <span className="text-xs font-mono bg-gray-50 border border-gray-200 text-gray-600 px-3 py-1.5 rounded-lg">
                        Selector: {issue.element}
                      </span>
                    </div>

                    {/* Location Tag & Visual Guide Callout */}
                    <div className="p-3.5 rounded-xl bg-blue-50/50 border border-blue-100 space-y-1.5">
                      <div className="flex items-center gap-2 text-xs font-bold text-blue-900">
                        <MapPin size={15} className="text-blue-600 flex-shrink-0" />
                        <span>Exact Page Location: <strong className="text-blue-700 bg-blue-100 px-2 py-0.5 rounded">{issue.pageZone}</strong></span>
                      </div>
                      {issue.visualGuide && (
                        <p className="text-xs text-blue-800 font-medium pl-6">
                          <strong>Visual Guide:</strong> {issue.visualGuide}
                        </p>
                      )}
                    </div>

                    {/* 3 User-Friendly Plain-English Cards for Non-Technical Visitors */}
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-3.5 pt-1">
                      {/* Simple Explanation */}
                      <div className="p-4 rounded-2xl bg-amber-500/10 border border-amber-200 shadow-2xs space-y-1.5 flex flex-col justify-between">
                        <div className="text-xs font-black text-amber-900 flex items-center gap-1.5 uppercase tracking-wider">
                          <span className="w-6 h-6 rounded-lg bg-amber-500 text-white flex items-center justify-center text-xs">🗣️</span>
                          Simple Explanation
                        </div>
                        <p className="text-xs text-amber-950 font-bold leading-relaxed">
                          {issue.simpleLanguage || issue.description}
                        </p>
                      </div>

                      {/* Main Problem */}
                      <div className="p-4 rounded-2xl bg-rose-500/10 border border-rose-200 shadow-2xs space-y-1.5 flex flex-col justify-between">
                        <div className="text-xs font-black text-rose-900 flex items-center gap-1.5 uppercase tracking-wider">
                          <span className="w-6 h-6 rounded-lg bg-rose-600 text-white flex items-center justify-center text-xs">⚠️</span>
                          Main Problem (Impact)
                        </div>
                        <p className="text-xs text-rose-950 font-bold leading-relaxed">
                          {issue.mainProblem || issue.description}
                        </p>
                      </div>

                      {/* After Fix Look */}
                      <div className="p-4 rounded-2xl bg-emerald-500/10 border border-emerald-200 shadow-2xs space-y-1.5 flex flex-col justify-between">
                        <div className="text-xs font-black text-emerald-900 flex items-center gap-1.5 uppercase tracking-wider">
                          <span className="w-6 h-6 rounded-lg bg-emerald-600 text-white flex items-center justify-center text-xs">✨</span>
                          After Fix Look & Behavior
                        </div>
                        <p className="text-xs text-emerald-950 font-bold leading-relaxed">
                          {issue.afterFixLook || issue.remediation}
                        </p>
                      </div>
                    </div>

                    {/* Side-by-Side Code Fix Comparison */}
                    <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
                      {/* Detected Non-Compliant HTML */}
                      <div className="p-4 bg-red-50/50 border border-red-200/80 rounded-xl space-y-2">
                        <div className="flex items-center justify-between text-xs font-bold text-red-700 uppercase tracking-wider">
                          <span>Detected Issue Snippet</span>
                          <span className="text-[10px] bg-red-100 px-2 py-0.5 rounded">Non-Compliant</span>
                        </div>
                        <pre className="text-xs font-mono text-red-900 bg-white p-3 rounded-lg border border-red-100 overflow-x-auto">
                          <code>{issue.snippet}</code>
                        </pre>

                        {issue.previewUrl && (
                          <div className="mt-2 relative rounded-lg overflow-hidden border border-red-200 shadow-xs bg-gray-100 group">
                            <img src={issue.previewUrl} alt="Non-compliant target banner preview" className="w-full h-28 object-cover filter brightness-90 group-hover:scale-105 transition-transform" />
                            <div className="absolute inset-0 bg-red-900/30 backdrop-blur-[1px] flex items-center justify-center p-2">
                              <span className="bg-red-600 text-white text-[10px] font-black uppercase tracking-wider px-3 py-1.5 rounded-full shadow-md flex items-center gap-1.5">
                                <AlertTriangle size={12} /> Target Image Preview (Missing ALT)
                              </span>
                            </div>
                          </div>
                        )}
                      </div>

                      {/* AI Remediation Fix */}
                      <div className="p-4 bg-emerald-50/50 border border-emerald-200/80 rounded-xl space-y-2 relative">
                        <div className="flex items-center justify-between text-xs font-bold text-emerald-700 uppercase tracking-wider">
                          <span className="flex items-center gap-1">
                            <Sparkles size={14} className="text-emerald-600" /> AI Suggested Code Fix
                          </span>
                          <button
                            onClick={() => handleCopyCode(issue.aiFix, issue.id)}
                            className="flex items-center gap-1 text-[11px] bg-white border border-emerald-200 hover:bg-emerald-100 text-emerald-800 px-2.5 py-1 rounded-md transition-all font-semibold cursor-pointer"
                          >
                            {copiedId === issue.id ? <Check size={13} /> : <Copy size={13} />}
                            {copiedId === issue.id ? 'Copied' : 'Copy Fix'}
                          </button>
                        </div>
                        <pre className="text-xs font-mono text-emerald-950 bg-white p-3 rounded-lg border border-emerald-100 overflow-x-auto">
                          <code>{issue.aiFix}</code>
                        </pre>
                      </div>
                    </div>

                    <div className="bg-primary/5 p-3 rounded-xl text-xs font-medium text-primary flex items-center justify-between gap-3 flex-wrap">
                      <div className="flex items-center gap-2">
                        <Zap size={14} className="flex-shrink-0" />
                        <span><strong>AI Guidance:</strong> {issue.remediation}</span>
                      </div>

                      {issue.stepByStepFix && (
                        <button
                          onClick={() => setExpandedStepId(expandedStepId === issue.id ? null : issue.id)}
                          className="flex items-center gap-1 text-[11px] font-bold text-primary hover:underline cursor-pointer bg-white px-2.5 py-1 rounded-lg border border-primary/20 shadow-2xs"
                        >
                          <HelpCircle size={13} />
                          {expandedStepId === issue.id ? 'Hide Action Plan' : 'How to Fix (3 Steps)'}
                        </button>
                      )}
                    </div>

                    {/* Expandable Step-by-Step Fix Accordion */}
                    {expandedStepId === issue.id && issue.stepByStepFix && (
                      <motion.div 
                        initial={{ opacity: 0, height: 0 }}
                        animate={{ opacity: 1, height: 'auto' }}
                        className="p-4 rounded-xl bg-gray-50 border border-gray-200 space-y-2 text-xs text-gray-800"
                      >
                        <div className="font-extrabold text-xs text-textMain uppercase tracking-wider flex items-center gap-1.5">
                          🛠️ Step-by-Step Fix Guide for {issue.id.toUpperCase()}
                        </div>
                        <ul className="space-y-1.5 pl-2 font-medium">
                          {issue.stepByStepFix.map((step, sIdx) => (
                            <li key={sIdx} className="flex items-start gap-2 text-gray-700">
                              <span>{step}</span>
                            </li>
                          ))}
                        </ul>
                      </motion.div>
                    )}
                  </div>
                ))}

                {filteredIssues.length === 0 && (
                  <div className="text-center py-12 text-textLight font-medium">
                    No issues found matching the "{activeFilter}" impact filter.
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </motion.div>
      )}

      {/* Passed WCAG 2.1 Rules Modal */}
      <AnimatePresence>
        {showPassedModal && (
          <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-xs">
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="bg-white rounded-3xl p-6 max-w-2xl w-full shadow-2xl space-y-4 max-h-[85vh] flex flex-col justify-between"
            >
              <div className="flex items-center justify-between border-b border-gray-100 pb-3">
                <div className="flex items-center gap-2.5">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/10 text-emerald-600 flex items-center justify-center">
                    <CheckCircle size={22} />
                  </div>
                  <div>
                    <h3 className="text-lg font-heading font-bold text-textMain">Passed WCAG 2.1 AA Rules Checklist</h3>
                    <p className="text-xs text-textLight font-medium">38 out of 43 evaluated accessibility rules passed on {url}</p>
                  </div>
                </div>
                <button 
                  onClick={() => setShowPassedModal(false)}
                  className="text-gray-400 hover:text-textMain font-bold text-lg p-1"
                >
                  ✕
                </button>
              </div>

              <div className="overflow-y-auto pr-1 space-y-3 flex-1">
                {[
                  { code: 'WCAG 1.2.1', title: 'Audio/Video Transcripts', desc: 'Pre-recorded media files have equivalent text transcripts available.' },
                  { code: 'WCAG 1.3.2', title: 'Meaningful DOM Order', desc: 'Screen reading sequence matches visual layout order.' },
                  { code: 'WCAG 1.4.1', title: 'Color Independence', desc: 'Information is not conveyed solely using visual color.' },
                  { code: 'WCAG 1.4.4', title: '200% Text Resizing', desc: 'Layout remains functional without overflow when zoomed 200%.' },
                  { code: 'WCAG 2.1.1', title: 'Keyboard Operability', desc: 'All links, buttons, and form controls are operable via keyboard.' },
                  { code: 'WCAG 2.1.2', title: 'No Keyboard Traps', desc: 'Keyboard focus can enter and exit all interactive components.' },
                  { code: 'WCAG 2.4.1', title: 'Skip to Content Link', desc: 'Valid "Skip to main content" link present for keyboard navigation.' },
                  { code: 'WCAG 2.4.2', title: 'Page Title', desc: 'Descriptive <title> tag present in HTML head.' },
                  { code: 'WCAG 3.1.1', title: 'Language Attribute', desc: 'HTML lang="en" attribute properly set.' },
                  { code: 'WCAG 4.1.1', title: 'Valid HTML Syntax', desc: 'No duplicate ID attributes or malformed DOM elements.' }
                ].map((rule, idx) => (
                  <div key={idx} className="p-3 rounded-xl bg-emerald-50/50 border border-emerald-100 flex items-start gap-3">
                    <CheckCircle size={16} className="text-emerald-600 flex-shrink-0 mt-0.5" />
                    <div>
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-mono font-bold text-emerald-800">{rule.code}</span>
                        <span className="text-xs font-bold text-textMain">{rule.title}</span>
                      </div>
                      <p className="text-xs text-gray-600 mt-0.5">{rule.desc}</p>
                    </div>
                  </div>
                ))}
              </div>

              <div className="pt-2 border-t border-gray-100 flex justify-end">
                <Button onClick={() => setShowPassedModal(false)}>Close Checklist</Button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
        </motion.div>
      )}
    </div>
  );
};

export default AIScanner;
