-- Clean and seed 29 real campus buildings based on ground accessibility research
DELETE FROM audit_responses;
DELETE FROM audits;
DELETE FROM maintenance_tasks;
DELETE FROM student_reports;
DELETE FROM evidence;
DELETE FROM buildings;
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (1, 'Zakir A', 'ZakirA', 'Zakir A (Zakir Husain Block) - Academic & facility infrastructure at Chandigarh University', 'South-West Campus, Zakir Zone', 5, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (2, 'Zakir B', 'ZakirB', 'Zakir B (Zakir Husain Block) - Academic & facility infrastructure at Chandigarh University', 'South-West Campus, Zakir Zone', 5, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (3, 'Zakir C', 'ZakirC', 'Zakir C (Zakir Husain Block) - Academic & facility infrastructure at Chandigarh University', 'South-West Campus, Zakir Zone', 5, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (4, 'NC 1', 'NC1', 'NC 1 (Nek Chand Block) - Academic & facility infrastructure at Chandigarh University', 'North Campus, Academic Complex', 6, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (5, 'NC 2', 'NC2', 'NC 2 (Nek Chand Block) - Academic & facility infrastructure at Chandigarh University', 'North Campus, Academic Complex', 6, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (6, 'NC 3', 'NC3', 'NC 3 (Nek Chand Block) - Academic & facility infrastructure at Chandigarh University', 'North Campus, Academic Complex', 6, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (7, 'NC 4', 'NC4', 'NC 4 (Nek Chand Block) - Academic & facility infrastructure at Chandigarh University', 'North Campus, Academic Complex', 6, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (8, 'NC 5', 'NC5', 'NC 5 (Nek Chand Block) - Academic & facility infrastructure at Chandigarh University', 'North Campus, Academic Complex', 6, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (9, 'D1', 'D1', 'D1 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (10, 'D2', 'D2', 'D2 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (11, 'D3', 'D3', 'D3 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (12, 'D4', 'D4', 'D4 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (13, 'D5', 'D5', 'D5 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (14, 'D6', 'D6', 'D6 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (15, 'D7', 'D7', 'D7 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (16, 'D8', 'D8', 'D8 (D Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block D', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (17, 'DD1', 'DD1', 'DD1 (DD Block) - Academic & facility infrastructure at Chandigarh University', 'East Campus, Extension Wing', 3, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (18, 'DD2', 'DD2', 'DD2 (DD Block) - Academic & facility infrastructure at Chandigarh University', 'East Campus, Extension Wing', 3, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (19, 'C1', 'C1', 'C1 (C Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block C', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (20, 'C2', 'C2', 'C2 (C Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block C', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (21, 'C3', 'C3', 'C3 (C Block) - Academic & facility infrastructure at Chandigarh University', 'Central Academic Ring, Block C', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (22, 'B1', 'B1', 'B1 (B Block) - Academic & facility infrastructure at Chandigarh University', 'West Academic Ring, Block B', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (23, 'B2', 'B2', 'B2 (B Block) - Academic & facility infrastructure at Chandigarh University', 'West Academic Ring, Block B', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (24, 'B3', 'B3', 'B3 (B Block) - Academic & facility infrastructure at Chandigarh University', 'West Academic Ring, Block B', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (25, 'B4', 'B4', 'B4 (B Block) - Academic & facility infrastructure at Chandigarh University', 'West Academic Ring, Block B', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (26, 'B5', 'B5', 'B5 (B Block) - Academic & facility infrastructure at Chandigarh University', 'West Academic Ring, Block B', 4, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (27, 'A1', 'A1', 'A1 (A Block) - Academic & facility infrastructure at Chandigarh University', 'Main Administrative & Academic Wing, Block A', 5, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (28, 'A2', 'A2', 'A2 (A Block) - Academic & facility infrastructure at Chandigarh University', 'Main Administrative & Academic Wing, Block A', 5, 'ACTIVE', NOW());
INSERT INTO buildings (id, building_name, building_code, description, location, number_of_floors, status, created_at) VALUES (29, 'A3', 'A3', 'A3 (A Block) - Academic & facility infrastructure at Chandigarh University', 'Main Administrative & Academic Wing, Block A', 5, 'ACTIVE', NOW());
SELECT setval('buildings_id_seq', (SELECT MAX(id) FROM buildings));

-- Ensure auditor is set to Vaibhav Tiwari
UPDATE users SET full_name = 'Vaibhav Tiwari' WHERE id = 3;

-- Insert completed RPWD Act 2016 Accessibility Audits for all 29 buildings with real audit dates and diverse statuses
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (1, 1, 3, '2026-07-06', 57.2, 'PENDING', 'RPWD Act 2016 physical accessibility audit conducted for Zakir A (Zakir Husain Block). Pending ramp and elevator floor announcement upgrades.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (2, 2, 3, '2026-07-09', 57.2, 'PENDING', 'RPWD Act 2016 physical accessibility audit conducted for Zakir B (Zakir Husain Block). Pending entrance ramp construction.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (3, 3, 3, '2026-07-14', 57.2, 'PENDING', 'RPWD Act 2016 physical accessibility audit conducted for Zakir C (Zakir Husain Block). Pending accessibility certification sign-off.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (4, 4, 3, '2026-07-18', 63.3, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for NC 1 (Nek Chand Block). Approved with 63.3% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (5, 5, 3, '2026-07-23', 61.2, 'PENDING', 'RPWD Act 2016 physical accessibility audit conducted for NC 2 (Nek Chand Block). Pending verification of tactile signage.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (6, 6, 3, '2026-07-28', 63.3, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for NC 3 (Nek Chand Block). Approved with 63.3% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (7, 7, 3, '2026-08-02', 63.3, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for NC 4 (Nek Chand Block). Approved with 63.3% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (8, 8, 3, '2026-08-06', 63.3, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for NC 5 (Nek Chand Block). Approved with 63.3% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (9, 9, 3, '2026-08-10', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D1 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (10, 10, 3, '2026-08-12', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D2 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (11, 11, 3, '2026-08-14', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D3 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (12, 12, 3, '2026-08-17', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D4 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (13, 13, 3, '2026-08-19', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D5 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (14, 14, 3, '2026-08-21', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D6 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (15, 15, 3, '2026-08-24', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D7 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (16, 16, 3, '2026-08-26', 74.8, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for D8 (D Block). Approved with 74.8% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (17, 17, 3, '2026-08-28', 41.6, 'REJECTED', 'RPWD Act 2016 physical accessibility audit conducted for DD1 (DD Block). Rejected due to lack of elevator access to upper floors.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (18, 18, 3, '2026-08-31', 41.6, 'REJECTED', 'RPWD Act 2016 physical accessibility audit conducted for DD2 (DD Block). Rejected due to severe barrier non-compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (19, 19, 3, '2026-09-03', 79.7, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for C1 (C Block). Approved with 79.7% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (20, 20, 3, '2026-09-07', 79.7, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for C2 (C Block). Approved with 79.7% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (21, 21, 3, '2026-09-10', 60.3, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for C3 (C Block). Approved with 60.3% compliance.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (22, 22, 3, '2026-09-12', 59.8, 'IN_PROGRESS', 'RPWD Act 2016 physical accessibility audit conducted for B1 (B Block). In progress - pathway and tactile improvements being completed.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (23, 23, 3, '2026-09-15', 59.8, 'IN_PROGRESS', 'RPWD Act 2016 physical accessibility audit conducted for B2 (B Block). In progress - washroom grab rail installations ongoing.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (24, 24, 3, '2026-09-17', 59.8, 'IN_PROGRESS', 'RPWD Act 2016 physical accessibility audit conducted for B3 (B Block). In progress - entrance ramp resurfacing.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (25, 25, 3, '2026-09-19', 59.8, 'IN_PROGRESS', 'RPWD Act 2016 physical accessibility audit conducted for B4 (B Block). In progress - elevator audio beacon integration.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (26, 26, 3, '2026-09-21', 59.8, 'IN_PROGRESS', 'RPWD Act 2016 physical accessibility audit conducted for B5 (B Block). In progress - signage installation in lobby.');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (27, 27, 3, '2026-09-22', 96.7, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for A1 (A Block). Approved - exemplary universal design compliance (96.7%).');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (28, 28, 3, '2026-09-24', 96.7, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for A2 (A Block). Approved - exemplary universal design compliance (96.7%).');
INSERT INTO audits (id, building_id, auditor_id, audit_date, overall_accessibility_score, status, remarks) VALUES (29, 29, 3, '2026-09-26', 96.7, 'APPROVED', 'RPWD Act 2016 physical accessibility audit conducted for A3 (A Block). Approved - exemplary universal design compliance (96.7%).');
SELECT setval('audits_id_seq', (SELECT MAX(id) FROM audits));

-- Realistic Student Reports across campus buildings
INSERT INTO student_reports (id, building_id, reporter_id, description, location_details, status, admin_notes, created_at, updated_at) VALUES 
(1, 1, 6, 'Entrance ramp slope exceeds 1:12 RPWD Act guideline near main portico. Wheelchair users require assistance.', 'Ground floor, main entrance portico', 'SUBMITTED', NULL, '2026-07-15 10:30:00', '2026-07-15 10:30:00'),
(2, 2, 7, 'Ground floor unisex accessible washroom door lock is jammed and grab bar is loose.', 'Ground floor, East Wing washroom', 'IN_PROGRESS', 'Work order issued to plumbing and fixtures team.', '2026-07-20 14:15:00', '2026-07-22 09:00:00'),
(3, 4, 8, 'Auditorium acoustic loop system is intermittently dropping signal during lectures.', '1st Floor, Main Lecture Auditorium', 'RESOLVED', 'Receiver and loop amplifier replaced and calibrated.', '2026-08-01 09:45:00', '2026-08-11 16:30:00'),
(4, 5, 9, 'Tactile paving leading to academic complex entrance has missing guiding tiles.', 'Pathway between Parking Lot 2 and Entrance', 'SUBMITTED', NULL, '2026-08-05 11:20:00', '2026-08-05 11:20:00'),
(5, 9, 6, 'Lift buttons lack braille embossment and audible speech floor indicators.', 'Central Lift Lobby, Cars A & B', 'IN_PROGRESS', 'Braille elevator control panel on backorder.', '2026-08-15 16:00:00', '2026-08-18 10:30:00'),
(6, 12, 7, 'Wheelchair ramp threshold at computer lab has a 2-inch step causing obstruction.', 'Floor 2, Computer Lab 204', 'RESOLVED', 'Rubber threshold transition bevel installed.', '2026-08-20 13:10:00', '2026-08-26 14:00:00'),
(7, 17, 8, 'No elevator available to reach second floor classrooms; stairs have no contrasting edge strips.', 'Main staircase between Ground and 2nd Floor', 'SUBMITTED', NULL, '2026-08-29 10:05:00', '2026-08-29 10:05:00'),
(8, 18, 9, 'Drinking water fountain height is 42 inches, inaccessible for seated students.', 'Floor 1, Corridor adjacent to Room 112', 'IN_PROGRESS', 'Dual-height accessible water dispenser requested.', '2026-09-02 15:30:00', '2026-09-04 11:15:00'),
(9, 19, 6, 'Classroom C102 desk rows are too narrow for standard wheelchair clearance (under 900mm).', 'Ground Floor, Lecture Hall C102', 'RESOLVED', 'Desks rearranged to provide dedicated 1000mm accessible aisle.', '2026-09-08 11:00:00', '2026-09-13 17:00:00'),
(10, 23, 7, 'Staircase handrail is missing on the left descending side between 2nd and 3rd floors.', 'Staircase B, North Wing', 'SUBMITTED', NULL, '2026-09-18 14:40:00', '2026-09-18 14:40:00'),
(11, 27, 8, 'Automatic sliding entrance door timing sensor closes too fast for slow-walking students.', 'Main Atrium Entrance Gate', 'RESOLVED', 'Motion sensor hold-open delay adjusted from 3s to 8s.', '2026-09-23 09:15:00', '2026-09-24 15:30:00'),
(12, 28, 9, 'High-contrast directional signage needed for low-vision visitors navigating to Dean''s office.', 'Floor 1, Administrative Wing Entrance', 'IN_PROGRESS', 'High-contrast yellow on charcoal signage scheduled for install.', '2026-09-25 12:00:00', '2026-09-25 17:00:00');

SELECT setval('student_reports_id_seq', (SELECT MAX(id) FROM student_reports));

-- Realistic Maintenance Tasks mapped to accessibility reports and audits
INSERT INTO maintenance_tasks (id, building_id, assignee_id, source_report_id, title, description, status, severity, priority, due_date, estimated_cost, created_at, updated_at) VALUES
(1, 1, 10, 1, 'Ramp gradient reconstruction at Zakir A', 'Re-engineer entrance ramp to 1:12 RPWD slope with dual continuous handrails at 750mm and 900mm.', 'OPEN', 'HIGH', 'HIGH', '2026-10-15', 45000.0, '2026-07-16 11:00:00', '2026-07-16 11:00:00'),
(2, 2, 11, 2, 'Accessible washroom hardware overhaul in Zakir B', 'Replace lock cylinder and reinforce wall anchor mounts for 35mm stainless steel grab rails.', 'IN_PROGRESS', 'MEDIUM', 'HIGH', '2026-10-05', 8500.0, '2026-07-21 15:00:00', '2026-07-23 10:00:00'),
(3, 4, 12, 3, 'Acoustic induction loop amplifier upgrade in NC 1', 'Calibrate hearing loop field strength to IEC 60118-4 standard across NC 1 auditorium.', 'RESOLVED', 'LOW', 'MEDIUM', '2026-08-10', 15000.0, '2026-08-02 10:00:00', '2026-08-11 16:30:00'),
(4, 5, 10, 4, 'Tactile guiding tile repair along NC 2 pathway', 'Replace damaged warning and directional blister paving on main approach route to NC 2.', 'OPEN', 'MEDIUM', 'MEDIUM', '2026-10-20', 12000.0, '2026-08-06 12:00:00', '2026-08-06 12:00:00'),
(5, 9, 11, 5, 'Braille elevator car operation panel for D1', 'Install COP with raised tactile numbers, braille code, and two-way visual/audible emergency intercom.', 'IN_PROGRESS', 'HIGH', 'HIGH', '2026-10-10', 65000.0, '2026-08-16 17:00:00', '2026-08-19 11:00:00'),
(6, 12, 12, 6, 'Threshold ramp bevel installation at D4 lab', 'Fit chamfered aluminum transition strip to eliminate vertical trip hazard at lab doorway.', 'RESOLVED', 'LOW', 'LOW', '2026-08-25', 3500.0, '2026-08-21 14:00:00', '2026-08-26 14:00:00'),
(7, 17, 10, 7, 'Staircase contrast strip application in DD1', 'Apply 50mm non-slip yellow photoluminescent contrast strips to all step nosings.', 'OPEN', 'CRITICAL', 'HIGH', '2026-10-08', 18000.0, '2026-08-30 11:00:00', '2026-08-30 11:00:00'),
(8, 18, 11, 8, 'Dual-height drinking water cooler retrofit for DD2', 'Install barrier-free drinking water unit with push-pad actuation at 800mm operating height.', 'IN_PROGRESS', 'HIGH', 'MEDIUM', '2026-10-18', 32000.0, '2026-09-03 16:00:00', '2026-09-05 12:00:00'),
(9, 19, 12, 9, 'Classroom accessible seating arrangement at C1', 'Configure designated 1000mm clear aisle and wheelchair companion seating in lecture hall C102.', 'RESOLVED', 'LOW', 'LOW', '2026-09-12', 2000.0, '2026-09-09 12:00:00', '2026-09-13 17:00:00'),
(10, 23, 10, 10, 'Dual handrail installation on B2 stairwell', 'Mount continuous 45mm circular brushed stainless steel handrails with 300mm wall extensions.', 'OPEN', 'MEDIUM', 'MEDIUM', '2026-10-25', 24000.0, '2026-09-19 15:00:00', '2026-09-19 15:00:00'),
(11, 27, 11, 11, 'Automatic sliding door radar sensor retiming at A1', 'Recalibrate microprocessor controller for 8-second dwell time and obstacle detection sensor.', 'VERIFIED', 'LOW', 'LOW', '2026-09-24', 1500.0, '2026-09-23 10:00:00', '2026-09-24 16:00:00'),
(12, 28, 12, 12, 'High-contrast tactile directory board for A2', 'Fabricate matte-finish acrylic wayfinding map with raised braille Grade 2 characters.', 'IN_PROGRESS', 'MEDIUM', 'MEDIUM', '2026-10-12', 16500.0, '2026-09-25 13:00:00', '2026-09-25 17:30:00');

SELECT setval('maintenance_tasks_id_seq', (SELECT MAX(id) FROM maintenance_tasks));
